version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Install aws cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws configure set default.region ${AWS_REGION}
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - run: 
          name: Compress Artifacts
          command: |
            echo "Current directory: "`pwd`
            mkdir -p lambda_functions
            cd lambda_functions
            cp ../resetpassword.js .
            zip -r lambda-${CIRCLE_BUILD_NUM}.zip .
      - run:
          name: Upload Artifacts to S3
          command: |
            ls -la
            cd lambda_functions
            aws configure list
            aws s3 cp lambda-${CIRCLE_BUILD_NUM}.zip ${CODE_DEPLOY_S3_BUCKET} --sse
      - run:
          name: AWS Lambda Update Function Code
          command: |
            pwd
            cd lambda_functions
            ls
            aws lambda update-function-code --function-name lambda_webapp --zip-file fileb://lambda-${CIRCLE_BUILD_NUM}.zip
            echo "code deployment complete"
            # aws deploy create-deployment --application-name csye6225-lambda --deployment-config-name CodeDeployDefault.LambdaAllAtOnce --deployment-group-name csye6225-lambda-deployment --revision '{"revisionType": "AppSpecContent", "appSpecContent": {"content": "{\"version\": 0.0,\"Resources\": [{\"webapp\": {\"Type\": \"AWS::Lambda::Function\",\"Properties\": {\"Name\": \"webapp\",\"Alias\": \"webapp\",\"CurrentVersion\": \"1\",\"TargetVersion\": \"2\"}}}]}"}}' --output text --query '[deploymentId]'
workflows:
    pr_check:
      jobs:
        - build